name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.89
          components: rustfmt, clippy
      - name: Install cargo-nextest
        run: cargo install cargo-nextest
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-features --lib -- -D warnings
      - name: Tests
        run: cargo nextest run --all-features --lib
