name: Daily Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.89
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install and start Ollama
        run: |
          curl -L https://ollama.ai/install.sh | sh
          ollama serve >/tmp/ollama.log 2>&1 &
          until curl -s http://127.0.0.1:11434/api/version >/dev/null; do
            sleep 1
          done
      - name: Build Ollama model
        run: |
          ollama create zc-forum-summarizer -f Modelfile
          ollama run zc-forum-summarizer "ping" >/tmp/ollama-warmup.log
      - name: Run digest
        env:
          LLM_MODEL: zc-forum-summarizer
          OLLAMA_BASE_URL: http://127.0.0.1:11434
        run: cargo run --release
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deploy
        uses: actions/deploy-pages@v4
